name = "example"
perm = "default"
rows = 3
title = "VelocityGUI"
empty = "AIR"
sound = "ENTITY_ARROW_HIT_PLAYER"

[items]
  [items.1]
    material = "OAK_SIGN"
    stack = 1
    name = "&dServer Rules"
    lore = [
      "&eRule breakers will be banned!"
    ]
    enchanted = true